### ISSUE TITLE
[Todo] Improved Push Security: connected apps & revoke, and explicit push permission for Sign Request & xApps

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#4]
Allow users to review all XUMM apps with push access, and allow a user to revoke push access. When revoking, somehow allow the user to report the app as well. Too many reports for a specific app = trigger (to XRPL Labs) to review the app.

- [ ] Add push permission to Sign Request (App, API)
- [ ] Add push permission request to xApp commands (SDK, App, API)
- [ ] Add settings with permissions & revoke (App, API)

### @WietseWind notes:

- App Endpoint: get all tokens, expiration, icon, title, description, permissions
- App Endpoint: assign/revoke perms: xApp push, revoke entire user token for app (revokes general push)
- App Payload: meta: show current permissions, so Sign in screen can reflect current status
- App endpoint PATCH (sign in): add permission fields (allow / disallow, also able to take away given perms)
- OTT: return perms
- OTT (xApp env): request perms (push)
- xApp SDK: request perms (push)

### Push Test scenarios
- Regular xApp
  - xApp Push
  - xApp Event + Push
  - Backend API: event with user token push
  - xApp JWT: event with push
  - Non xApp JWT (OAuth2): event with push
- Permissioned (xApp / regular app)

**Comment by WietseWind** [comment]
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/4756161/212894540-65c952a8-bd5e-46cb-8c0d-5c8f7315a028.png">

```
SELECT
  applications.application_uuidv4_txt,
  applications.application_name,
  applications.application_description,
  applications.application_icon_url,
  applications.application_infourl_homepage,
  applications.application_infourl_terms,
  applications.application_infourl_support,
  applications.application_infourl_privacy,
  tokens.token_days_valid as token_days_valid_after_last_signed_payload,
  tokens.token_issued,
  tokens.token_expiration,
  0 as ask_to_report_application
FROM
  tokens
LEFT JOIN
  applications ON (tokens.application_id = applications.application_id)
WHERE
  user_id = 754562
AND
  token_hidden < 1
AND
  token_reported < 1
AND
  token_expiration > CURRENT_TIMESTAMP
ORDER BY
  token_expiration ASC
```
